# Generated by Django 2.2.1 on 2019-08-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(default='', max_length=255)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('business_shortcode', models.CharField(default='0', max_length=255)),
                ('bill_ref_number', models.CharField(default='', max_length=255)),
                ('account_balance', models.CharField(max_length=255)),
                ('msisdn', models.CharField(max_length=255)),
                ('checkout_request_id', models.CharField(max_length=255)),
                ('merchant_request_id', models.CharField(default='', max_length=255)),
                ('required_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('indicator_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('result_code', models.IntegerField(default=1)),
                ('password', models.CharField(default='', max_length=100)),
                ('timestamp', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
