# Generated by Django 2.2.1 on 2019-08-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_auto_20190811_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
