# Generated by Django 2.2.1 on 2019-08-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Group', max_length=64, unique=True)),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('required_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contributions', models.ManyToManyField(blank=True, to='contributions.Contribution')),
            ],
        ),
    ]
