# Generated by Django 2.2.1 on 2019-06-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Group', max_length=64, unique=True)),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('contributions', models.ManyToManyField(to='contributions.Contribution')),
            ],
        ),
    ]
