# Generated by Django 2.2.1 on 2019-06-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='group',
        ),
    ]
