# Generated by Django 2.2.1 on 2019-06-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_remove_contribution_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='business_shortcode',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
