# Generated by Django 2.2.1 on 2019-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_auto_20190630_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
