# Generated by Django 2.2.1 on 2019-06-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamaa', '0006_remove_chamaa_contribution'),
        ('contributions', '0003_contribution_business_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='chamaa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chamaa.Chamaa'),
        ),
    ]
