# Generated by Django 2.2.1 on 2019-06-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamaa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamaa',
            name='phone_number',
        ),
    ]
