# Generated by Django 2.2.1 on 2019-06-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamaa',
            name='contributions',
            field=models.ManyToManyField(null=True, to='contributions.Contribution'),
        ),
    ]
