# Generated by Django 2.2.1 on 2019-06-18 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_remove_contribution_group'),
        ('chamaa', '0002_remove_chamaa_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamaa',
            name='contribution',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contributions.Contribution'),
        ),
    ]
