# Generated by Django 2.2.1 on 2019-06-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamaa', '0005_auto_20190619_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamaa',
            name='contribution',
        ),
    ]
