# Generated by Django 2.2.1 on 2019-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamaa', '0006_remove_chamaa_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamaa',
            name='phone_number',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
